task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:
    - name: Linux, GCC 9.5
      container:
        image: gcc:9.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev python3-pytest

  test_script: uname -rms && python3 --version && cmake ${CMAKE_OPTIONS:-} -B build -S . && cmake --build build && ${SUDO:-} cmake --install build && cmake --build build --target check
