task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:
    - name: FreeBSD 14.0
      freebsd_instance:
        image_family: freebsd-14-0-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 14.0, shared libraries
      freebsd_instance:
        image_family: freebsd-14-0-snap
      environment:
        CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=ON
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 13.2
      freebsd_instance:
        image_family: freebsd-13-2
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 13.2, shared libraries
      freebsd_instance:
        image_family: freebsd-13-2
      environment:
        CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=ON
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 12.4
      freebsd_instance:
        image_family: freebsd-12-4-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3

    - name: Linux, GCC 8.5
      container:
        image: gcc:8.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev
    - name: Linux, GCC 9.5
      container:
        image: gcc:9.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev
    - name: Linux, GCC 10.4
      container:
        image: gcc:10.4
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 11.3
      container:
        image: gcc:11.3
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 12.2
      container:
        image: gcc:12.2
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 13.2
      container:
        image: gcc:13.2
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3

    - name: macOS, Homebrew
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      environment:
        # To quote Homebrew, "bison is keg-only, which means it was not
        # symlinked into /usr/local, because some formulae require a newer
        # version of bison." I do not know when this became the case as it was
        # not originally, but we'll force this.
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
        SUDO: sudo
      install_script: brew update && brew install bison && brew link bison --force

    - name: macOS, Macports
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
        SUDO: sudo
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison

  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake ${CMAKE_OPTIONS:-} .. && cmake --build . && ${SUDO:-} cmake --build . -- install && cmake --build . -- check
