task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:
    - name: FreeBSD 15.0
      freebsd_instance:
        image_family: freebsd-15-0-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 15.0, shared libraries
      freebsd_instance:
        image_family: freebsd-15-0-snap
      environment:
        CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=ON
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 14.0
      freebsd_instance:
        image_family: freebsd-14-0-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 14.0, shared libraries
      freebsd_instance:
        image_family: freebsd-14-0-snap
      environment:
        CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=ON
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 13.3
      freebsd_instance:
        image_family: freebsd-13-3
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 13.3, shared libraries
      freebsd_instance:
        image_family: freebsd-13-3
      environment:
        CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=ON
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3

    - name: Linux, GCC 8.5
      container:
        image: gcc:8.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev
    - name: Linux, GCC 9.5
      container:
        image: gcc:9.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev
    - name: Linux, GCC 10.5
      container:
        image: gcc:10.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 11.4
      container:
        image: gcc:11.4
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 12.3
      container:
        image: gcc:12.3
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 13.3
      container:
        image: gcc:13.3
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, GCC 14.1
      container:
        image: gcc:14.1
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3
    - name: Linux, ARM, GCC 14.1
      arm_container:
        image: gcc:14.1
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3

    - name: macOS, Homebrew
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sonoma
      environment:
        # To quote Homebrew, "bison is keg-only, which means it was not
        # symlinked into /usr/local, because some formulae require a newer
        # version of bison." I do not know when this became the case as it was
        # not originally, but we'll force this.
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
        SUDO: sudo
      install_script: uname -rms && brew update && brew install bison && brew link bison --force

    - name: macOS, Macports
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sonoma
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
        SUDO: sudo
      install_script: uname -rms && ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison

  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -rms && python3 --version && cmake ${CMAKE_OPTIONS:-} -B build -S . && cmake --build build && ${SUDO:-} cmake --install build && cmake --build build --target check
