task:

  # only test the master branch and pull requests
  only_if: $CIRRUS_BRANCH == "master" || $CIRRUS_PR != ""

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:
    - name: FreeBSD 13.0
      freebsd_instance:
        image_family: freebsd-13-0-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 12.2
      freebsd_instance:
        image_family: freebsd-12-2-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3
    - name: FreeBSD 11.3
      freebsd_instance:
        image_family: freebsd-11-3-snap
      install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3

    - name: Linux, GCC 8.5
      container:
        image: gcc:8.5
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev
    - name: Linux, GCC 9.4
      container:
        image: gcc:9.4
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev
    - name: Linux, GCC 10.3
      container:
        image: gcc:10.3
      environment:
        DEBIAN_FRONTEND: noninteractive
        CXXFLAGS: -pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y bison cmake libfl-dev libgmp-dev libxml2-utils strace z3

    - name: macOS, XCode 11.3.1, Homebrew
      osx_instance:
        image: catalina-xcode-11.3.1
      environment:
        # To quote Homebrew, "bison is keg-only, which means it was not
        # symlinked into /usr/local, because some formulae require a newer
        # version of bison." I do not know when this became the case as it was
        # not originally, but we'll force this.
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      # The version of Bison that comes with XCode is too old to support some of
      # the flags/features we use. To install newer versions and make them
      # available to CMake we need to link them into the system directories.
      install_script: brew update && brew install bison && brew link bison --force
    - name: macOS, XCode 11.4.1, Homebrew
      osx_instance:
        image: catalina-xcode-11.4.1
      environment:
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: brew update && brew install bison && brew link bison --force
    - name: macOS, XCode 11.5, Homebrew
      osx_instance:
        image: catalina-xcode-11.5
      environment:
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: brew update && brew install bison && brew link bison --force
    - name: macOS, XCode 11.6, Homebrew
      osx_instance:
        image: catalina-xcode-11.6
      environment:
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: brew update && brew install bison && brew link bison --force
    - name: macOS, XCode 12.0, Homebrew
      osx_instance:
        image: catalina-xcode-12.0
      environment:
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: brew update && brew install bison && brew link bison --force
    - name: macOS, XCode 12.1, Homebrew
      osx_instance:
        image: catalina-xcode-12.1
      environment:
        PATH: /usr/local/opt/bison/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: brew update && brew install bison && brew link bison --force

    - name: macOS, XCode 11.3.1, Macports
      osx_instance:
        image: catalina-xcode-11.3.1
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison
    - name: macOS, XCode 11.4.1, Macports
      osx_instance:
        image: catalina-xcode-11.4.1
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison
    - name: macOS, XCode 11.5, Macports
      osx_instance:
        image: catalina-xcode-11.5
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison
    - name: macOS, XCode 11.6, Macports
      osx_instance:
        image: catalina-xcode-11.6
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison
    - name: macOS, XCode 12.0, Macports
      osx_instance:
        image: catalina-xcode-12.0
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison
    - name: macOS, XCode 12.1, Macports
      osx_instance:
        image: catalina-xcode-12.1
      environment:
        PATH: /opt/local/bin:${PATH}
        CXXFLAGS: -fsanitize=address -Werror
      install_script: ./misc/install-macports.sh && sudo port -v selfupdate && sudo port -N install bison

  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- install && cmake --build . -- check
