#!/usr/bin/env bash

# test that we can generate and run a basic model via rumur-run

if [ -z "${AUTOPKGTEST_TMP}" ]; then
  printf 'AUTOPKGTEST_TMP not set; not running in autopkgtest?\n' >&2
  exit 1
fi

set -e
set -x

# move to temporary directory
mkdir -p ${AUTOPKGTEST_TMP}/rumur-run-model
cd ${AUTOPKGTEST_TMP}/rumur-run-model

# construct a simple model
cat - >model.m <<EOT
var
  x: boolean;

startstate begin
  x := true;
end;

rule begin
  x := !x;
end;
EOT

# use rumur-run to compile and run it
rumur-run model.m
