/* this code was generated by Murphi2C */

#include <inttypes.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* built-in boolean type */
typedef bool boolean;


static void failed_assertion_(const char *message) {
  fprintf(stderr, "failed assertion: %s\n", message);
  exit(EXIT_FAILURE);
}

void (*failed_assertion)(const char*) = failed_assertion_;

static void failed_assumption_(const char *message) {
  fprintf(stderr, "failed assumption: %s\n", message);
  exit(EXIT_FAILURE);
}

void (*failed_assumption)(const char*) = failed_assumption_;

static void error_(const char *message) {
  fprintf(stderr, "error: %s\n", message);
  exit(EXIT_FAILURE);
}

void (*error)(const char*) = error_;

static void cover_(const char *message __attribute__((unused))) {
}

void (*cover)(const char*) = cover_;

static void liveness_(const char *message __attribute__((unused))) {
}

void (*liveness)(const char*) = liveness_;

// various printf wrappers to deal with the user having passed --value-type
static __attribute__((unused)) void print_int     (int v)      { printf("%d\n",          v); }
static __attribute__((unused)) void print_unsigned(unsigned v) { printf("%u\n",          v); }
static __attribute__((unused)) void print_short   (short v)    { printf("%hd\n",         v); }
static __attribute__((unused)) void print_long    (long v)     { printf("%ld\n",         v); }
static __attribute__((unused)) void print_int8_t  (int8_t v)   { printf("%" PRId8  "\n", v); }
static __attribute__((unused)) void print_uint8_t (uint8_t v)  { printf("%" PRIu8  "\n", v); }
static __attribute__((unused)) void print_int16_t (int16_t v)  { printf("%" PRId16 "\n", v); }
static __attribute__((unused)) void print_uint16_t(uint16_t v) { printf("%" PRIu16 "\n", v); }
static __attribute__((unused)) void print_int32_t (int32_t v)  { printf("%" PRId32 "\n", v); }
static __attribute__((unused)) void print_uint32_t(uint32_t v) { printf("%" PRIu32 "\n", v); }
static __attribute__((unused)) void print_int64_t (int64_t v)  { printf("%" PRId64 "\n", v); }
static __attribute__((unused)) void print_uint64_t(uint64_t v) { printf("%" PRIu64 "\n", v); }


