#!/usr/bin/env bash

# does the compiler support -mcx16?


# try to compile something using -mcx16
${CC:-cc} -x c -std=c11 -mcx16 -o /dev/null - &>/dev/null <<EOT
int main(void) {
  return 0;
}
EOT

# see if the compiler errored
if [ $? -eq 0 ]; then
  printf 'True\n'
else
  printf 'False\n'
fi
