Document: rumur
Title: Debian rumur Manual
Author: <insert document author here>
Abstract: This manual describes what rumur is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rumur/rumur.sgml.gz

Format: postscript
Files: /usr/share/doc/rumur/rumur.ps.gz

Format: text
Files: /usr/share/doc/rumur/rumur.text.gz

Format: HTML
Index: /usr/share/doc/rumur/html/index.html
Files: /usr/share/doc/rumur/html/*.html
