.TH MURPHI2XML 1
.SH NAME
murphi2xml \- Print the abstract syntax tree of a parsed Murphi model
.SH SYNOPSIS
.B \fBmurphi2xml\fR [\fB--output\fR \fIFILE\fR | \fB-o\fR \fIFILE\fR] \fIFILE\fR
.SH DESCRIPTION
The utility \fBmurphi2xml\fR is bundled with the model checker Rumur and can
be used to translate a Murphi model into its abstract syntax tree in an XML
format. See
.BR rumur(1)
For more information about Rumur or Murphi.
.SH OPTIONS
\fB--help\fR or \fB-?\fR
.RS
Display usage information.
.RE
.PP
\fB--output\fR \fIFILE\fR or \fB-o\fR \fIFILE\fR
.RS
Set the path to write the output XML to. If this argument is omitted, output is
written to standard out.
.RE
.PP
\fB--version\fR
.RS
Display version information and exit.
.RE
.SH SEE ALSO
rumur(1)
