.TH RUMUR-RUN 1
.SH NAME
rumur \- Yet another explicit state model checker
.SH SYNOPSIS
.B \fBrumur-run\fR \fBoptions...\fR
.SH DESCRIPTION
As a convenient way to run \fBrumur\fR, the wrapper \fBrumur-run\fR is provided.
It runs \fBrumur\fR with the given options, compiles the generated verifier and then
runs it. See
.BR rumur(1)
for available options.
.SH SEE ALSO
rumur(1)
