name: Linux CI
permissions: {}
on:
  pull_request:
    branches:
      - main
jobs:
  ubuntu2204_gcc10_x86-64:
    name: Ubuntu 22.04, GCC 10, x86-64
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-10
      CXX: g++-10
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2204_x86-64:
    name: Ubuntu 22.04, GCC 11 (default), x86-64
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2204_gcc12_x86-64:
    name: Ubuntu 22.04, GCC 12, x86-64
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-12
      CXX: g++-12
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2404_x86-64:
    name: Ubuntu 24.04, GCC 13 (default), x86-64
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2404_gcc14_x86-64:
    name: Ubuntu 24.04, GCC 14, x86-64
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-14
      CXX: g++-14
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2404_gcc12_aarch64:
    name: Ubuntu 24.04, GCC 12, aarch64
    runs-on: ubuntu-24.04-arm
    env:
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-12
      CXX: g++-12
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2404_aarch64:
    name: Ubuntu 24.04, GCC 13 (default), aarch64
    runs-on: ubuntu-24.04-arm
    env:
      DEBIAN_FRONTEND: noninteractive
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
  ubuntu2404_gcc14_aarch64:
    name: Ubuntu 24.04, GCC 14, aarch64
    runs-on: ubuntu-24.04-arm
    env:
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-14
      CXX: g++-14
      CXXFLAGS: -pedantic -Werror -Wno-error=overloaded-virtual -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install libfl-dev libxml2-utils python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: echo "checking out ${{ github.event.pull_request.head.sha }}"
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: sudo cmake --install build
      - run: cmake --build build --target check
